<a href="https://colab.research.google.com/github/guadalupe-santos/ALC-Laboratorios/blob/main/labo02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Ejercicio 1

In [25]:
import numpy as np
def rota(θ):
  a = np.cos(θ)
  b = np.sin(θ)
  T = np.array([[a,-b],[b,a]])
  return T
rota(0.5*np.pi)

array([[ 6.123234e-17, -1.000000e+00],
       [ 1.000000e+00,  6.123234e-17]])

In [26]:
def escala(s):
  T = []
  for i in range(0,len(s)):
    fila = []
    for j in range(0,len(s)):
      if j == i:
        fila.append(s[j])
      else:
        fila.append(0)
    T.append(fila)
  return np.array(T)
escala([2,3])

array([[2, 0],
       [0, 3]])

In [27]:
def rota_y_escala(θ,s):
  T = escala(s) @ rota(θ)
  return T
rota_y_escala(0.5*np.pi,[2,3])

array([[ 1.2246468e-16, -2.0000000e+00],
       [ 3.0000000e+00,  1.8369702e-16]])

In [29]:
def afin(θ,s,b):
  A = rota_y_escala(θ,s)
  T = np.array([[A[0,0],A[0,1],b[0]],
                [A[1,0],A[1,1],b[1]],
                 [0,0,1]])
  return T


afin(0.5*np.pi,[2,3],[1,2])

array([[ 1.2246468e-16, -2.0000000e+00,  1.0000000e+00],
       [ 3.0000000e+00,  1.8369702e-16,  2.0000000e+00],
       [ 0.0000000e+00,  0.0000000e+00,  1.0000000e+00]])

In [41]:
def trans_afin(v,θ,s,b):
  T = afin(θ,s,b)
  #Corrigo dimensión la dimensión del vector
  v3 = np.append(v,1)
  x = T[0]@v3
  y = T[1]@v3
  xy = []
  xy.append(x)
  xy.append(y)
  return xy

trans_afin([1,2],0.5*np.pi,[2,3],[1,2])

[np.float64(-3.0), np.float64(5.0)]

In [42]:
#TEST
assert(np.allclose(rota(0), np.eye(2)))
assert(np.allclose(rota(np.pi/2), np.array([[0, -1],[1, 0]])))
assert(np.allclose(rota(np.pi), np.array([[-1, 0],[0, -1]])))

# Tests para escala
assert(np.allclose(escala([2,3]), np.array([[2,0],[0,3]])))
assert(np.allclose(escala([1,1,1]), np.eye(3)))
assert(
    np.allclose(escala([0.5,0.25]), np.array([[0.5,0],[0,0.25]]))
)

# Tests para rota_y_escala
assert(
    np.allclose(rota_y_escala(0,[2,3]), np.array([[2,0],[0,3]]))
)
assert(np.allclose(
    rota_y_escala(np.pi/2,[1,1]), np.array([[0,-1],[1,0]])
))
assert(np.allclose(
    rota_y_escala(np.pi,[2,2]), np.array([[-2,0],[0,-2]])
))

# Tests para afin
assert(np.allclose(
    afin(0,[1,1],[1,2]),
    np.array([[1,0,1],
              [0,1,2],
              [0,0,1]])))
assert(np.allclose(afin(np.pi/2,[1,1],[0,0]),
    np.array([[0,-1,0],
              [1,0,0],
              [0,0,1]])))
assert(np.allclose(afin(0,[2,3],[1,1]),
    np.array([[2,0,1],
              [0,3,1],
              [0,0,1]])))

# Tests para trans_afina

assert(np.allclose(
    trans_afin(np.array([1,0]), np.pi/2,[1,1],[0,0]),
    np.array([0,1])
))
assert(np.allclose(
    trans_afin(np.array([1,1]), 0,[2,3],[0,0]),
    np.array([2,3])
))
assert(np.allclose(
    trans_afin(np.array([1,0]), np.pi/2,[3,2],[4,5]),
    np.array([4,7])
))

print("¡Todos los tests del Laboratorio 2 han pasado exitosamente!")

¡Todos los tests del Laboratorio 2 han pasado exitosamente!
